# Generated by Django 3.1.7 on 2021-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=10)),
                ('location', models.CharField(max_length=120)),
                ('review', models.IntegerField()),
            ],
        ),
    ]
